networks:
  logging:
    driver: bridge

services:
  order.api:
    image: ${DOCKER_REGISTRY-}orderapi
    build:
      context: .
      dockerfile: Order/src/Order.API/Dockerfile
    entrypoint: [ "sh", "-c", "dotnet Order.API.dll" ]
    networks:
      - logging

  fluentbit:
    image: fluent/fluent-bit:3.2.8
    container_name: fluentbit
    volumes:
      - ./config/fluentbit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./config/parsers.conf:/fluent-bit/etc/parsers.conf
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "24224:24224"
    networks:
      - logging

  opensearch:
    image: opensearchproject/opensearch:2.19.1
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Thisisnotsecure0@
    ports:
      - "9200:9200"
      - "9600:9600"
    networks:
      - logging

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.19.1
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      - OPENSEARCH_HOSTS=["http://opensearch:9200"]
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    depends_on:
      - opensearch
    networks:
      - logging
  